### ISSUE TITLE
all: 统一图片文件

### ISSUE THREAD

**Issue by chai2010** [chai2010/advanced-go-programming-book#119]
确保是自己画的，禁止复制/粘贴网上图片

**Comment by cch123** [comment]
我这边目前只有一张网图，web 完结后会换掉

**Comment by chai2010** [comment]
官网的架构图是可以用的。但是普通的博客文章的图片最后不要用。
有别人头像的不能使用

**Comment by chai2010** [comment]
1-4章图片已经清理了非官方的第三方图片，只保留了一些从官网或者规范文档中直接引用的图片。
