### ISSUE TITLE
ch1-05-mem.md中，顺序一致性内存模型 部分 有误

### ISSUE THREAD

**Issue by allenwind** [chai2010/advanced-go-programming-book#165]
ch1-basic章
ch1-05-mem.md中，顺序一致性内存模型 部分

“当然，通过sync.Mutex互斥量也是可以实现同步的”下面的代码段：

	go func(){
		println("你好, 世界")
		mu.Unock()
	}()

应该为：
	go func(){
		println("你好, 世界")
		mu.Unlock()
	}()

少了`l`

**Comment by chai2010** [comment]
已修复，感谢
