### ISSUE TITLE
Ch1.1 Erlang并发编程模型

### ISSUE THREAD

**Issue by kailiangji** [chai2010/advanced-go-programming-book#190]
## Expected Behavior
Erlang的并发编程模型是Actor，是与CSP类似但又不同的模型，

**Comment by chai2010** [comment]
原文强调Erlang是csp的另一种实现，了解这个语言的人应该能够理解就是actor。不过本书目标读者是Go用户，我想Go用户是不太在意Erlang具体是怎么实现这种细节问题的。

如果没有异议的话，稍后会关闭
