### ISSUE TITLE
1.4 函数定义问题

### ISSUE THREAD

**Issue by kailiangji** [chai2010/advanced-go-programming-book#203]
1.4中的函数Find定义是有点问题的。对于map[key]的返回值默认是一个，如果使用value, ok := map[key] 可以返回两个值，一个是key所对应的值，另一个是key在map中是否存在。但是如果使用return map[key]， 只能返回value。所以 Find 函数需要改成
```
func Find(m map[int]int, key int) (value int, ok bool) {
	value, ok = m[key]
	return
}
```

**Comment by chai2010** [comment]
已经修复。感谢
