### ISSUE TITLE
gitbook目录首页没有翻译

### ISSUE THREAD

**Issue by chai2010** [chai2010/advanced-go-programming-book#228]
readme 部分应该为 “介绍”，可能是gitbook的问题

![snip20180806_1](https://user-images.githubusercontent.com/2295542/43691435-32ce7458-994f-11e8-81ed-3aae7870096c.png)

**Comment by chai2010** [comment]
https://github.com/GitbookIO/gitbook/issues/2104

**Comment by zhuxiaoxi** [comment]
我从gitbook那里过来的，这个好像可以直接改成自己想要的内容
![image](https://user-images.githubusercontent.com/2098464/45611564-69ee0c00-ba92-11e8-9c42-682e1a780cac.png)

**Comment by chai2010** [comment]
能否提供修改的方案？或者提交pr帮忙改下？
谢谢🙏

**Comment by zhuxiaoxi** [comment]
我其他的gitbook都是这么写的，看起来很正常。尝试改了一下，但没有效果。
![image](https://user-images.githubusercontent.com/2098464/45613627-83df1d00-ba99-11e8-8f96-79fc63d6d733.png)
