### ISSUE TITLE
从哪能看到目录？

### ISSUE THREAD

**Issue by choleraehyq** [chai2010/advanced-go-programming-book#23]
第二章完了直接就第六章了，中间的章节是怎么安排的？

**Comment by chai2010** [comment]
之前的想法是中间可能有swig，汇编等章节，第六章也不是绝对等最终方案。
现在以实际完成的章节为准，章节没有详细的安排，最终具体顺序可调整。
当然，如果有什么建议或需求可以讨论

**Comment by chai2010** [comment]
重新将目录捋捋一遍，可以看这里：
https://github.com/chai2010/advanced-go-programming-book/blob/master/SUMMARY.md
