### ISSUE TITLE
1.5.4节 初始化顺序

### ISSUE THREAD

**Issue by tongjichao** [chai2010/advanced-go-programming-book#253]
里面写到如果某个init函数内部用go关键字启动了新的goroutine的话，新的goroutine只有在进入main.main函数后才被执行到。测试如下：
```
 package main
  import (
	  "fmt"
	     "time"
   )

var channel = make(chan int, 1)

func init() {
	fmt.Println("init...")

	go func() {
		fmt.Println("go func")
		channel <- 1
	}()
	time.Sleep(time.Second * time.Duration(2))
}

func main() {
	fmt.Println("main...")
	<-channel
}

测试输出是init...，go func，main...
按照描述我理解输出应该是init,main,gofunc
```

**Comment by chai2010** [comment]
你的理解是对对。所有对gofunc只能在main之后被启动。

**Comment by tongjichao** [comment]
你好，如果init内部的go func 需要等到main函数执行后才能执行，那上面的测试用例应该是先打印main，然后再打印gofunc吧，实际上测试是先打印gofunc，再打印main.

**Comment by tongjichao** [comment]
代码修改如下
```
package main

import (
	"fmt"
	"time"
)

func init() {
	fmt.Println("init...")

	go func() {
		fmt.Println("go func")
		time.Sleep(time.Second * time.Duration(2))
	}()
	time.Sleep(time.Second * time.Duration(2))
	fmt.Println("init print after Sleep")
}

func main() {
	fmt.Println("main...")
}
```
实际上输出结果是
init...
go func
init print after Sleep
main...
说明这个init 的go  func 是在init 内部中直接就执行了，并没有等待main.main启动后执行。
测试的golang版本go version go1.10.3 darwin/amd64

**Comment by cch123** [comment]
go func的执行时机是不确定的，要看调度器。而且既然官方都这么说了，那随时修改实现也是可以的

逻辑上不要依赖这种**不确定**的顺序

**Comment by cch123** [comment]
@chai2010 ，要是 spec 里没这么说可能这么写确实不合适哇

**Comment by chai2010** [comment]
我个人比较认可一个方式：以spec为准，runtime之上一个符合spec的实现。对于一个代码的输出，可以正确某个程序是错误的，但是无法证明某个程序是正确的。对于并发的程序，不能以有限的运行次数来证明并发程序执行的顺序，需要找到明确的反例或证据。

因此，并发程序，要能从代码静态分析出运行结果（就像数学家那样，一支笔和一张纸，不需要电脑辅助）。

**Comment by sheepbao** [comment]
你说的`进入main函数的时刻：gofunc和main的打印在2个goroutine运行，这2个事件是并发的，谁都可能先发生`这个是对的，但是原文`如果某个init函数内部用go关键字启动了新的goroutine的话，新的goroutine只有在进入main.main函数后才被执行到`这句话是错的。

**Comment by chai2010** [comment]
@sheepbao 你是对的。

`新的goroutine只有在进入`main.main`函数之后才可能被执行到`描述是错误的。
改为`新的goroutine和`main.main`函数是并发执行的`。

帮忙看看这样描述是否准确？

**Comment by sheepbao** [comment]
@chai2010 嗯嗯，比如runtime.main叫G1（这里执行main.main）和init的新生成的goroutine叫G2，这里的G1和G2就是并发运行的。

**Comment by chai2010** [comment]
谢谢
