### ISSUE TITLE
序言：一句话有错误

### ISSUE THREAD

**Issue by polaris1119** [chai2010/advanced-go-programming-book#257]
在序言：

> 目前国内互联网公司的新兴相互已经在逐渐向Go语言生态转移，大型分布式系统的开发实战经验也是大家关心的技术。

"新兴相互" 是错误吧。

> 大型分布式系统的开发实战经验也是大家关心的技术 

建议去掉最后的 “技术”

"本书针对Go语言有一定经验" 此句建议：本书针对有一定Go语言经验“

**Comment by xuqiang1015** [comment]
新兴**相互**，猜测应该是新兴**项目**

**Comment by chai2010** [comment]
欢迎提交pr
