### ISSUE TITLE
第一章语言基础中的鸭子对象

### ISSUE THREAD

**Issue by xuqiang1015** [chai2010/advanced-go-programming-book#261]
文中：
`对以函数、方法和接口所体现的面向过程和鸭子对象的编程`
只接触过**鸭子类型**，**鸭子对象**感觉表意不准确，本书中提到的也多是**鸭子类型**，以及鸭子面向对象，此处改为**鸭子类型**更为贴切

**Comment by chai2010** [comment]
欢迎提交pr

**Comment by chai2010** [comment]
没有反馈，暂时关闭。如果需要再打开
