### ISSUE TITLE
中间件小问题

### ISSUE THREAD

**Issue by 7Ethan** [chai2010/advanced-go-programming-book#269]
第五章 

5.3 middleware中间件

(我下载过来的pdf在425页) `main`函数中的 `http.HandleFunc("/",	timeMiddleware(hello))`实际上是不能编译通过的,建议修改 `http.Handle("/", timeMiddleware(http.HandlerFunc(hello)))`

**Comment by cch123** [comment]
@7Ethan ，谢谢，已修正~
