### ISSUE TITLE
关于调用独立的C文件的一个问题

### ISSUE THREAD

**Issue by twojin** [chai2010/advanced-go-programming-book#27]
![2](https://user-images.githubusercontent.com/31733409/34557015-cd786dc6-f173-11e7-944f-7ed01801264a.png)
调用独立C文件时按例子报错如下:
![1](https://user-images.githubusercontent.com/31733409/34556974-936c8f2c-f173-11e7-9484-56300b7752ca.png)

我在函数声明上面引入c文件就好了, 请问下这个是什么问题?

**Comment by chai2010** [comment]
确保打开了cgo选项，然后先go build构建，然后再执行生成的可执行文件

**Comment by twojin** [comment]
明白了, 我是直接go run 的所以需要引入c文件, go build会构建目录下所有的包所以不需要这一句.
