### ISSUE TITLE
关于 cgo 中内存部分的讨论

### ISSUE THREAD

**Issue by ClarkGuan** [chai2010/advanced-go-programming-book#272]
第2章第7节

https://github.com/chai2010/advanced-go-programming-book/blob/master/ch2-cgo/ch2-07-memory.md

有几个问题：

1、字符串取index后是无法再取地址的。例如代码中所写

`C.printString((*C.char)(unsafe.Pointer(&s[0])))`

&s[0] 部分有问题。

2、Go 字符串没有 C 字符串的结尾 '\0'，所以代码

`func main() {
    s := "hello"
    printString(s)
}`

替换为

`func main() {
    s := "hello\u0000"
    printString(s)
}`

是不是合适？

3、我不知道我理解的对不对，如果某个 goroutine 代码运行时调用 cgo 代码，那么这个 goroutine 所在操作系统线程就会被这个 C 函数 “占用”，goroutine 处于 “暂停” 状态，直到 C 函数执行完成并返回，这个时候被 “ 暂停” 的 goroutine “复活” ，继续执行。所以无论 C 函数执行多长时间，只要它不返回，调用它的 goroutine 就不可能继续执行，为什么还会有 goroutine 的栈分配操作呢？这块是我无法理解的地方，所以中间一段讨论我没看懂。

**Comment by chai2010** [comment]
关于一二，请参考这个pr的回复
https://github.com/chai2010/advanced-go-programming-book/pull/226

**Comment by chai2010** [comment]
关于第三点，我不清楚你指的是文中具体那个段落。我猜测了一种情形（不一定会真的出现），goroutine引用了其它goroutine栈上某个变量的地址，然后传人了c函数。这时候会出现被C函数依赖的每个goroutine栈上的变量被锁定。。。。

关键还是要确认下你的第三点问题是什么

**Comment by chai2010** [comment]
1/2 问题已经修复

**Comment by chai2010** [comment]
没有反馈就先关闭了，如果需要再重现打开
