### ISSUE TITLE
2.6.3 改进：闭包函数作为比较函数

### ISSUE THREAD

**Issue by Shimingli** [chai2010/advanced-go-programming-book#275]
提示：哪一章节的问题，建议如何修改
import "sort"

func main() {
	values := []int32{42, 9, 101, 95, 27, 25}

	sort.Slice(values,  less func(i, j int) bool {
		return values[i] < values[j]
	})

	fmt.Println(values)
}

这个地方 less 这个关键字可以不要

**Comment by Shimingli** [comment]
不对 应该是不能要，要了就报错了 
![image](https://user-images.githubusercontent.com/20720544/43881012-543175e2-9bdd-11e8-96aa-170132ef30de.png)

**Comment by Shimingli** [comment]
不过  大佬 辛苦了   学无止境

**Comment by chai2010** [comment]
欢迎提交pr
