### ISSUE TITLE
all: 代码路径要继续简化

### ISSUE THREAD

**Issue by chai2010** [chai2010/advanced-go-programming-book#284]
import pkg “ch2/3-1” 这种格式，便于和文章引用代码编号

**Comment by chai2010** [comment]
```go
import pkg1 "ch2-03/01"
import pkg2 "ch2-04/02"

```

**Comment by chai2010** [comment]
确实不符号编码规范。不过这样做的主要原因是为了文中代码编号规范化，比如代码 ch2-03/01 这样。

目录一般对于main包，其它的包都是子目录下，子目录可以根据代码命名。

PS：改进原则，为了文中代码编号简单。

**Comment by chai2010** [comment]
有个不好的消息，正规图书中格式是 2-3 表示第二章第三个图，不包含节编号

**Comment by chai2010** [comment]
2-3 这种方式，从代码目录将无法知道属于哪个节。因此需要增加一个 doc.go，里面标注属于哪个节

**Comment by fuwensun** [comment]
图片索引一般时这样的 “第几章-第几图”，例子代码不用再改动了吧？！

**Comment by fuwensun** [comment]
例子代码目前的格式这么理解对吧： ch第几章-第几节/第几小节

**Comment by chai2010** [comment]
图 2-3；代码 2-4。目前的代码目录还需要调整。我稍后第一章会尝试改几个，可以参考

**Comment by chai2010** [comment]
参考 ch1-01。 

图片 用了 1-1-go-family-tree.png 和 1-2-go-log4.png 这种格式，前面的 1-1 和 1-2 是图的索引编号，后缀部分是未来避免图片丢失名字信息（文中可见的图编号是没有后缀信息的）。

代码部分，vendor/1-1 是第一章第一个完整的代码编号（不完整的代码片段可能需要忽略，需要进一步确认）。目录里面的 main.go 对于main包的代码。doc_ch1-01.go 表示这个编号目录下的代码是 ch1-01 节的代码。

PS: 目前还剩余的问题是不完整的代码片段是否要进行编号？

**Comment by chai2010** [comment]
@fuwensun 编号问题先暂时不要修改。我觉得目前的改动方案都不太好（正规的编号不适合代码管理，适合代码管理的和正规编号不一致）。我想可能需要写一个小工具来自动完成这个转换工作。

**Comment by chai2010** [comment]
@fuwensun QQ给你发了消息，有时间上线下，有问题讨论

**Comment by chai2010** [comment]
```go
import "chai2010.cn/gobook/ch3/1-1"
```

基于模块特性

**Comment by chai2010** [comment]
https://godoc.org/chai2010.cn/gobook
