### ISSUE TITLE
1.5.2原子操作代码问题

### ISSUE THREAD

**Issue by gitwillsky** [chai2010/advanced-go-programming-book#296]
提示：哪一章节的问题，建议如何修改

```go
var total struct {
    sync.Mutex
    value int
}
```

修改为
```go
var total struct {
    *sync.Mutex
    value int
}
```

**Comment by chai2010** [comment]
修改的原因是什么？

**Comment by gitwillsky** [comment]
我的理解：total.Lock() 编译后为 total.Mutex.Lock()， Lock()方法的接收者是(m *Mutex)，如果声明为`sync.Mutex`，如果这个total作为参数，则在并发的环境下会有问题。

大佬，不知道我的理解对不对？

**Comment by gitwillsky** [comment]
看来我脑洞太大了，作为参数的情况，也是声明为*total。
