### ISSUE TITLE
ch4: 是否要增加nginx一节内容？

### ISSUE THREAD

**Issue by chai2010** [chai2010/advanced-go-programming-book#319]
grpc代理和负载均衡等

**Comment by cch123** [comment]
和后面的负载均衡可能会显得重复，如果要加负载均衡可以扩展一下之前的那节

**Comment by chai2010** [comment]
不过这是一个比较大的话题。或许在 `ch4.6 GRPC和Protobuf扩展` 简单提下 Nginx 对 grpc 的扩展即可。Nginx用户可能就是直接使用，不关心原理了。

ch6.5 部分的负载均衡可能更侧重于实现的原理。如果扩展的话，会涉及 nginx和grpc 的组合吗？

**Comment by chai2010** [comment]
PS: 突然提这个，是因为刚发现我们的一个新开发的系统居然好像开始用了Nginx的grpc代理特性。

**Comment by chai2010** [comment]
ch4.6 末尾增加了一段简单说明。
