### ISSUE TITLE
英文版

### ISSUE THREAD

**Issue by lai32290** [chai2010/advanced-go-programming-book#325]
请问这本书有英文版的吗？

**Comment by cch123** [comment]
没有哦

**Comment by lai32290** [comment]
太可惜了，其实是我的朋友要的，但是他是巴西人。还是非常感谢

**Comment by chai2010** [comment]
这是开源的书，欢迎提供英文翻译啊

**Comment by chai2010** [comment]
重复，请参考 https://github.com/chai2010/advanced-go-programming-book/issues/342
