### ISSUE TITLE
ch6-08-control-flow.png 图片有问题

### ISSUE THREAD

**Issue by fuwensun** [chai2010/advanced-go-programming-book#334]
https://github.com/chai2010/advanced-go-programming-book/blob/master/images/ch6-08-control-flow.png
![image](https://user-images.githubusercontent.com/15542874/44461411-52626580-a643-11e8-818d-291d6aa83749.png)

这张图有问题，CLD三层，最后一层

**Comment by cch123** [comment]
啊。。确实画错了 orz

**Comment by cch123** [comment]
已修正

**Comment by fuwensun** [comment]
![image](https://user-images.githubusercontent.com/15542874/44471638-e68df600-a65e-11e8-8e0f-5040c246e7a8.png)


离上一张不远的地方还有一张
