### ISSUE TITLE
ch6-08-control-flow-2.png 有问题

### ISSUE THREAD

**Issue by fuwensun** [chai2010/advanced-go-programming-book#336]
https://github.com/chai2010/advanced-go-programming-book/blob/master/images/ch6-08-control-flow-2.png
![image](https://user-images.githubusercontent.com/15542874/44471940-982d2700-a65f-11e8-895e-87d271e24247.png)

离上一张不远的地方还有一张

**Comment by cch123** [comment]
fixed, https://github.com/chai2010/advanced-go-programming-book/commit/4504ac94221671c2806e2e0b0b0a2a109f88d360

画图的时候粗心了 orz
