### ISSUE TITLE
ch-3-4-func

### ISSUE THREAD

**Issue by Frozen-Shadow** [chai2010/advanced-go-programming-book#338]
3.4.4 中，关于栈帧中局部变量位置描述
>而局部变量中先定义的变量c离伪SP寄存器对应的地址最远，最后定义的变量a离伪SP寄存器最近。有两个因素导致出现这种逆序的结果：一个从Go语言函数角度理解，先定义的a变量地址要比后定义的变量的地址更小；另一个是伪SP寄存器对应栈帧的底部，而X86中栈是从高向地生长的，所以最先定义有着更小地址的c变量离栈的底部伪SP更远。

1.描述好像和 图3.4.4 有些冲突
2.typo 
 - 一个从Go语言函数角度理解，先定义的a变量地址要比后定义的变量的地址更小
 - 一个从Go语言函数角度理解，先定义的**c**变量地址要比后定义的变量的地址更小

**Comment by cch123** [comment]
局部变量可以随便放

这里说的早定义的离伪 SP 最远，其实说的是你的 Go 程序 --> 编译 --> 汇编，这种逻辑下的情况，因为确实 Go 代码里在前面定义的变量虚拟内存地址要比后面定义的小一些。

如果是你自己手写汇编，其实怎么排列都行

**Comment by Frozen-Shadow** [comment]
感谢回复。

```
func Foo() {
	var c []byte
	var b int16
	var a bool
}
```
这里的局部变量 `c []byte` 是先定义的，但是看图却是离伪sp 更近一些。

![image](https://user-images.githubusercontent.com/8757196/44629412-a2159980-a981-11e8-9609-a2cb73b4132c.png)

**Comment by cch123** [comment]
https://github.com/chai2010/advanced-go-programming-book/pull/340
