### ISSUE TITLE
附录： 不同Goroutine之间不满足顺序一致性内存模型

### ISSUE THREAD

**Issue by wanyaoqi** [chai2010/advanced-go-programming-book#359]
@chai2010 我认为你这个观点是错的
https://github.com/chai2010/advanced-go-programming-book/blame/7cd7095b14eb3d94918f28905a9bcee63a304ff7/appendix/appendix-a-trap.md#L188
你在这里设置cpu个数为1又设置了死循环，让main函数的goroutine独占了cpu
另外一个goroutine并不能设置done的值，所以进程无法退出

go应该不会不遵循一致性内存模型

加上GoSched验证：
```
package main

import "runtime"

var msg string

var done bool = false

func main() {
	runtime.GOMAXPROCS(1)
	go func() {
		println("go go")
		msg = "hello, world"
		done = true
		runtime.Gosched()
	}()
	for {
		runtime.Gosched()
		if done {
			println(msg)
			break
		}
	}
}
```

**Comment by chai2010** [comment]
goroutine中的`done = true`可能无法被main函数的goroutine看到。

你的例子即使能够输出正确的结果，也无法证明这个程序永远都能产生正确的结果。
以代码来证明程序看似正确是很多人经常犯的错误。

一个严禁的并发代码，运行逻辑应该不会受到`runtime.Gosched()`、`time.Sleep()`等函数的影响。
否则很可能就是错误的并发程序

**Comment by wanyaoqi** [comment]
上面那段代码中在goroutine中 `println("go go")` ;
如果把runtime.Gosched()去掉将看不到 打印`go go`

**Comment by chai2010** [comment]
注意我前面的回复：一个正确的并发程序不应该依靠手工调用sched或sleep来保证正确性！否则程序就是有问题的。

因此我可以推断你的程序是有问题的。

**Comment by wanyaoqi** [comment]
你好， 可能是你没有理解我的意思
如下代码， 按照 《不同Goroutine之间不满足顺序一致性内存模型》你这个观点是会打印`go go` 然后阻塞。
但是实际上他不会打印`go go`， 是应为这个goroutine没有被调度到，main函数的线程独占了cpu。
```go
package main

import "runtime"

var msg string

var done bool = false

func main() {
	runtime.GOMAXPROCS(1)
	go func() {
		println("go go")
		msg = "hello, world"
		done = true
	}()
	for {
		if done {
			println(msg)
			break
		}
	}
}
```
如果你真的认为 《不同Goroutine之间不满足顺序一致性内存模型》，请证明

**Comment by chai2010** [comment]
我一直以为这是每个Gopher都知道的常识，没想到给大家造成了这么大的困惑。

例子中的`runtime.GOMAXPROCS(1)`确实干扰了用户，不过并不是为了证明这个结论。
例子是为了展示错误的使用方法（请暂时忽略`runtime.GOMAXPROCS(1)`语句）。

通过代码来正确这个结论并不容易，不过官方的文档已经有了定义，可以当作是公理。
请仔细阅读 https://golang.org/ref/mem 倒数第二个例子代码后面的注释：

```
As before, there is no guarantee that, in main, observing the write to done implies observing the write to a, so this program could print an empty string too. Worse, there is no guarantee that the write to done will ever be observed by main, since there are no synchronization events between the two threads. The loop in main is not guaranteed to finish.
 ```

语言的内存模式规范不保证这种用法的正确性，因此这是一个错误的用法。

但是错误的代码，并不是时刻都能展示错误的结果。

**Comment by wanyaoqi** [comment]
你好，可能你书中的例子表达的意思不正确，让我以为在一个goroutine中修改一个全局变量，另一个goroutine不能感知。
建议你换一个例子（比如上面那个例子）

**Comment by chai2010** [comment]
例子确实有点不友好，欢迎提交pr

**Comment by wanyaoqi** [comment]
> 例子确实有点不友好，欢迎提交pr

Willing to
