### ISSUE TITLE
冲突

### ISSUE THREAD

**Issue by felix0080** [chai2010/advanced-go-programming-book#373]
提示：哪一章节的问题，建议如何修改
1.3.2节，字符串 开头第二句话 
每个字符串的长度虽然也是固定的，但是字符串的长度并不是字符串类型的一部分
疑问
后面写到了
字符串结构由两个信息组成：第一个是字符串指向的底层字节数组，第二个是字符
串的字节的长度。字符串其实是一个结构体
请问这两句话一个说长度不是类型的一部分，一个又指明是一部分冲突了吗
？？？

**Comment by chai2010** [comment]
比如下面2个不同长度的字符串:

```go
var s1 = "abc"
var s2 = "abcdef"

s1 = s2
```

其中s1和s2长度不同, 但是都是string类型.
因此可以用s2对应的字符串给s1变量赋值.

同样的情况, 如果换成数组就不行了, 因为长度是数组类型的组成部分.

**Comment by felix0080** [comment]
哦哦，谢谢，我懂你说的意思了，是和上面的数组对比
