### ISSUE TITLE
0长切片

### ISSUE THREAD

**Issue by felix0080** [chai2010/advanced-go-programming-book#375]
提示：哪一章节的问题，建议如何修改
1.3切片
切片内存技巧
函数实现利用了0长切片的特性，实现高效而且简洁。
func TrimSpace(s []byte) []byte {
      b := s[:0]
      for _, x := range s {
            if x != ' ' {
                  b = append(b, x)
            }
      }
      return b
}
这里说的高效 是指 b:=s[:0]这句话 是b的cap等于s的cap，但长度为0 ，append的时候没有额外分配的意思吗

**Comment by chai2010** [comment]
是的，复用了原始的内存

**Comment by felix0080** [comment]
好
