### ISSUE TITLE
内容错误

### ISSUE THREAD

**Issue by felix0080** [chai2010/advanced-go-programming-book#379]
提示：哪一章节的问题，建议如何修改
235页 末
其中BP用于记录当前函数帧的开始位置，和函数调用相关的指令会
隐式地影响SP的值；SP则对应当前栈指针的位置，和栈相关的指令会隐式地影响
SP的值；
其中 前半段应该是隐式影响BP的值

**Comment by chai2010** [comment]
235页是哪一节啊?

**Comment by felix0080** [comment]
3.2.3 X86-64体系结构

**Comment by chai2010** [comment]
看到了, 能帮忙提下pr吗? 谢谢
