### ISSUE TITLE
3.3.2.5 string类型变量

### ISSUE THREAD

**Issue by felix0080** [chai2010/advanced-go-programming-book#380]
3.3.2.5 string类型变量
程序运行报错
---
GLOBL ·Helloworld(SB),$16
GLOBL text<>(SB),$16
DATA text<>+0(SB)/8,$"Hello Wo"
DATA text<>+8(SB)/8,$"rld!"
DATA ·Helloworld+0(SB)/8,$text<>(SB) // StringHeader.Data
DATA ·Helloworld+8(SB)/8,$12 // StringHeader.Len
---
# command-line-arguments
text: missing Go type information for global symbol: size 16

**Comment by felix0080** [comment]
应该这样改
#include "textflag.h"
GLOBL ·Helloworld(SB),$16
GLOBL text<>(SB),NOPTR,$16
DATA text<>+0(SB)/8,$"Hello Wo"
DATA text<>+8(SB)/8,$"rld!"
DATA ·Helloworld+0(SB)/8,$text<>(SB) // StringHeader.Data
DATA ·Helloworld+8(SB)/8,$12 // StringHeader.Len

**Comment by chai2010** [comment]
是少了noptr吧，欢迎提交pr
