### ISSUE TITLE
ch3: Swap执行有问题

### ISSUE THREAD

**Issue by felix0080** [chai2010/advanced-go-programming-book#382]
func Swap(a int8,b int8)(c int8,d int8)
请问这个函数对应的汇编应该怎么写，对应内存的结构应该是怎样的，我以为是2 2 2 2 ，但是是错误的
TEXT ·Swap(SB),$0-8
    MOVQ a+0(FP),AX
    MOVQ b+2(FP),BX
    MOVQ BX,c+4(FP)
    MOVQ AX,d+6(FP)
    RET

6 0
Process finished with exit code 0

**Comment by chai2010** [comment]
3.2.5节，找对应的mov指令

**Comment by felix0080** [comment]
将汇编改成一个字节 函数输入1，2 返回 0 0，正确值应该是 2，1
TEXT ·Swap(SB),$0-4
    MOVQ a+0(FP),AX
    MOVQ b+1(FP),BX
    MOVQ BX,c+2(FP)
    MOVQ AX,d+3(FP)
    RET

**Comment by felix0080** [comment]
int64是没有问题的，也就是原文中int 是对的，但是我想试试int8,没想到交换不了

**Comment by chai2010** [comment]
确实是有个对齐的问题, 书中没有解释清楚.

先构造一个Go的例子:

```go
//go:nosplit
//go:noinline
func Swap(a, b int8) (c, d int8) {
	return b, a
}
```

禁止inline和栈分裂是为了简化输出的汇编代码, 便于理解.

下面的命令查看生成的汇编:

```
$ go tool compile -S x.go
        0x0000 00000 (b.go:5)   TEXT    "".Swap2(SB), NOSPLIT, $0-16
        0x0000 00000 (b.go:5)   FUNCDATA        $0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
        0x0000 00000 (b.go:5)   FUNCDATA        $1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
        0x0000 00000 (b.go:5)   FUNCDATA        $3, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
        0x0000 00000 (b.go:6)   MOVBLZX "".b+9(SP), AX
        0x0005 00005 (b.go:6)   MOVB    AL, "".c+16(SP)
        0x0009 00009 (b.go:6)   MOVBLZX "".a+8(SP), AX
        0x000e 00014 (b.go:6)   MOVB    AL, "".d+17(SP)
        0x0012 00018 (b.go:6)   RET
```

忽略`FUNCDATA`部分(那是给运行时的数据, 并不是机器指令), 大概简化如下:

```
TEXT "".Swap(SB), NOSPLIT, $0-16
    MOVBLZX "".b+9(SP), AX
    MOVB    AL, "".c+16(SP)
    MOVBLZX "".a+8(SP), AX
    MOVB    AL, "".d+17(SP)
    RET
```

可以发现Swap函数的大小是16个字节. a和c差了8个字节, b和d也差了8个字节.
差8个字节的原因是, a是输入参数的开始位置, 必须对齐到8字节, c是返回值的开始位置, 也必须对齐到8字节.
对于任何一个函数来说, 准确定位参数和返回值的内存地址是第一重要的事情.

然后就是1字节的int8数据如何加载到8字节大小的寄存器中,
8字节大小的寄存器如何保存1字节到内存中.

查看 ch3.2.5的指令部分, 可以找到 `MOVBQZX` 指令, 表示加载1字节到8字节的寄存器, 高位用零填充.
(MOVBQZX是MOV-B-Q-Z-X的缩写, MOV是移动, B是byte, Q是四个word, 一个word两个字节, Z是zero表示0填充).
然后是`MOVB`, 将寄存器保存到1个字节的内存, 高位部分被丢弃.

最终整理的代码如下:

```
TEXT ·Swap(SB), $0
	MOVBQZX a+0(FP), AX         // AX = a
	MOVBQZX b+1(FP), BX         // BX = b
	MOVB    BX     , ret0+8(FP) // ret0 = BX
	MOVB    AX     , ret1+9(FP) // ret1 = AX
	RET
```

**Comment by chai2010** [comment]
书中关于返回值部分讲的有问题, 没有说明返回值需要重新对齐.

**Comment by felix0080** [comment]
醍醐灌顶

**Comment by felix0080** [comment]
正确了，谢谢！

**Comment by chai2010** [comment]
https://github.com/chai2010/advanced-go-programming-book/commit/6ad677111b58084ebc169786b676e947124eff5a
