### ISSUE TITLE
3.5节 顺序执行 汇编执行错误

### ISSUE THREAD

**Issue by felix0080** [chai2010/advanced-go-programming-book#384]
TEXT ·main(SB),$24-0
    MOVQ $0,a-8*2(SP)
    MOVQ $0,b-8*1(SP)

    MOVQ $10,AX
    MOVQ AX,a-8*2(SP)

    MOVQ AX,0(SP)
    CALL runtime·printint
    CALL runtime·printnl

    MOVQ a-8*2(SP),AX
    MOVQ b-8*1(SP),BX

    MOVQ AX,BX
    ADDQ BX,BX
    MULQ AX,BX
    MOVQ BX,b-8*1(SP)

    MOVQ BX,0(SP)
    CALL runtime·printint
    CALL runtime·printnl
    RET
执行报错
undefined label runtime.printint
asm: invalid instruction: 00070 CALL
asm: invalid instruction: 00070 CALL
asm: invalid instruction: 00086 MULQ	AX, BX
asm: invalid instruction: 00095 CALL
asm: invalid instruction: 00095 CALL
asm: assembly failed

**Comment by chai2010** [comment]
@cch123 Go1.11是不是发生什么变化?

**Comment by cch123** [comment]
是原来程序写的有问题吧
改成我这样试试

```go
#include "textflag.h"

TEXT ·main(SB), $24-0
	MOVQ $0, a-8*2(SP) // a = 0
	MOVQ $0, b-8*1(SP) // b = 0

	// 将新的值写入a对应内存
	MOVQ $10, AX       // AX = 10
	MOVQ AX, a-8*2(SP) // a = AX

	// 以a为参数调用函数
	MOVQ AX, 0(SP)
	CALL	runtime·printint(SB)
	CALL	runtime·printnl(SB)

	// 函数调用后, AX/BX 寄存器可能被污染, 需要重新加载
	MOVQ a-8*2(SP), AX // AX = a
	MOVQ b-8*1(SP), BX // BX = b

	// 计算b值, 并写入内存
	MOVQ AX, BX        // BX = AX  // b = a
	ADDQ BX, BX        // BX += BX // b += a
	IMULQ AX, BX        // BX *= AX // b *= a
	MOVQ BX, b-8*1(SP) // b = BX

	// 以b为参数调用函数
	MOVQ BX, 0(SP)
	CALL runtime·printint(SB)
	CALL runtime·printnl(SB)

	RET

```

**Comment by chai2010** [comment]
@cch123 确实是少了`(SB)`后缀.

不过有一个问题,  `MULQ`为何不能用?
我看有这个指令: https://golang.org/src/cmd/internal/obj/x86/anames.go

**Comment by chai2010** [comment]
查指令知道原因了, MULQ默认是隐含操作AX, 因此只能有一个寄存器.

可以改成下面两个指令:

```s
MULQ BX         // AX = AX*BX
MOVQ AX, BX // BX = AX
```

IMULQ的写法不知道是x64支持的, 还是Go编译器做了转换.

**Comment by chai2010** [comment]
https://github.com/chai2010/advanced-go-programming-book/commit/e33e4100f2338a0287d16fd16a366993da325d81

**Comment by felix0080** [comment]
非常感谢！原来MULQ隐含了一步操作，谢谢chai哥和cch123

**Comment by chai2010** [comment]
https://github.com/chai2010/advanced-go-programming-book/commit/dc4b9a251cfa6e8879119e36cf07fd35bb5b1ee6
