### ISSUE TITLE
1.5.3 顺序一致性内存模型代码解释感觉有点问题

### ISSUE THREAD

**Issue by parsonscp** [chai2010/advanced-go-programming-book#394]
提示：哪一章节的问题，建议如何修改
[1.5.3 顺序一致性内存模型](https://github.com/chai2010/advanced-go-programming-book/blob/master/ch1-basic/ch1-05-mem.md#153-%E9%A1%BA%E5%BA%8F%E4%B8%80%E8%87%B4%E6%80%A7%E5%86%85%E5%AD%98%E6%A8%A1%E5%9E%8B)
原文对此的解释如下:Go语言并不保证在main函数中观测到的对done的写入操作发生在对字符串a的写入的操作之后，因此程序很可能打印一个空字符串。更糟糕的是，因为两个线程之间没有同步事件，setup线程对done的写入操作甚至无法被main线程看到，main函数有可能陷入死循环中。
下一段又说在Go语言中，同一个Goroutine线程内部，顺序一致性内存模型是得到保证的。如果下面的说法正确的话就可以保证对a的写入一定是在对done的写入之前,所以不可能发生打印空字符串的情况.

**Comment by chai2010** [comment]
setup和main不在一个Goroutine中，也就是在不同的宇宙中。
1个宇宙发生的事情，另一个宇宙可能永远都看不到。

**Comment by cch123** [comment]
不同的 goroutine 可能运行在不同的 cpu 核心，不做显式同步的话，可能核心会一直读取自己 L1 cache 里的值，所以可能两个核心里同一个变量的值永远都不一样

想要深入理解的话，建议去看看 mesi 协议
