### ISSUE TITLE
征集草根名言，每章一段

### ISSUE THREAD

**Issue by chai2010** [chai2010/advanced-go-programming-book#397]
感谢大家的关注，《Go语言高级编程》是完全通过开源的方式才完成的。
我们希望在每一章的开头放一个端草根名言，每个名言会有署名（github的ID也可以）。

本书大概在元旦之前交稿，欢迎大家参与🙏

**Comment by chai2010** [comment]
比如：

> 过去的经验往往是走向未来的枷锁，因为在过气技术中投入的沉没成本会阻碍人们拥抱新技术。
> -- chai2010

**Comment by khlipeng** [comment]
哥敲得不是代码，而是寂寞。

**Comment by chai2010** [comment]
@khlipeng 最好不要太常见的，不然容易引起署名争议的。

还有，如果人数超过，也不一定都能用上。
还请大家包涵。

**Comment by 3dgen** [comment]
曾经一度因未能习得C++令人眼花缭乱的新标准而痛苦不已；Go语言“少既是多”大道至简的理念让我重拾信心，寻回了久违的编程的乐趣。

--Ending

**Comment by cch123** [comment]
能跑就行
by rfyiamcook

**Comment by khlipeng** [comment]
学习编程，重要的是什么？多练、多看、多实践！
跨语言学习，掌握基础语法和语言的特性之后，实战，效率来的最快！

**Comment by Prnyself** [comment]
敢于发表自己的见解，敢于讨论

**Comment by hustlihaifeng** [comment]
被别人指出问题时，别管别人能不能做到，看别人说的对不对，然后完善自己。别人能不能做到是别人的事情，自己能不能做到关系到自己能否发展的更好。

**Comment by huiyanghu12** [comment]
跟对人，做对事。
                        by Rhichy

**Comment by kenrong** [comment]
不管何种编程语言，适合自己的就是最好的。不管何种编程语言，能稳定实现业务逻辑的就是最好的。世间编程语言千千万，世间程序猿万万千，能做到深入理解并应用的就是最好的。

**Comment by chai2010** [comment]
已经差不多了，谢谢🙏

**Comment by 469856321** [comment]
我不知道，你过去10年为什么不快乐。但相信我，抛掉过去的沉重，使用 golang ，体会最初的快乐！

**Comment by 7Ethan** [comment]
搬砖民工总会建成自己的罗马帝国。
by 小张

**Comment by gingerhot** [comment]
只有成功人士才关注性能。
— by 某知乎被屏蔽用户

**Comment by chai2010** [comment]
人数已经超出了。暂时先锁定了。

**Comment by chai2010** [comment]
ch1

我不知道，你过去10年为什么不快乐。但相信我，抛掉过去的沉重，使用 golang ，体会最初的快乐！
-- 469856321

搬砖民工也会建成自己的罗马帝国。
by 小张

ch2

过去的经验往往是走向未来的枷锁，因为在过气技术中投入的沉没成本会阻碍人们拥抱新技术。
-- chai2010

曾经一度因未能习得C++令人眼花缭乱的新标准而痛苦不已；Go语言“少既是多”大道至简的理念让我重拾信心，寻回了久违的编程乐趣。
-- Ending

ch3

能跑就行，不行加机器
-- rfyiamcool & 爱学习的孙老板
跟对人，做对事。
by Rhichy

ch4

学习编程，重要的是什么？多练、多看、多实践！
跨语言学习，掌握基础语法和语言的特性之后，实战，效率来的最快！
-- khlipeng

ch5

不管何种编程语言，适合自己的就是最好的。不管何种编程语言，能稳定实现业务逻辑的就是最好的。世间编程语言千千万，世间程序猿万万千，能做到深入理解并应用的就是最好的。
-- kenrong

ch6

被别人指出问题时，别管别人能不能做到，看别人说的对不对，然后完善自己。别人能不能做到是别人的事情，自己能不能做到关系到自己能否发展的更好。
--- hustlihaifeng 

没有选中的部分

只有成功人士才关注性能。
— by 某知乎被屏蔽用户

原因：知乎争议

敢于发表自己的见解，敢于讨论
-- Prnyself

原因：主题太大，某种特殊的原因

**Comment by chai2010** [comment]
解除锁定。

大概超出了1倍，不过我还是希望能够尽量全部包含，因此有些章节放了多个。
其中 “-- rfyiamcool & 爱学习的孙老板” 的两个太短，我合并为一个了。

感谢大家的参与，对于没有选中的 gingerhot 和 Prnyself 表示歉意。

已经选中的，麻烦确认下自己的署名。

**Comment by fanqinghui** [comment]
程序员没有高低之分，只有勤动手的程序员与懒动手的程序员之分！ -- fanqinghui

**Comment by chai2010** [comment]
已经全了，感谢大家关注

**Comment by pierre94** [comment]
发一个替补：有梦想谁都了不起
