### ISSUE TITLE
2.2.1 疑问

### ISSUE THREAD

**Issue by felix0080** [chai2010/advanced-go-programming-book#416]
2.2.1中说 构建cgo辅助函数时，不同虚拟C包之间是不能通用的，这个没错，但是我在当前包使用辅助函数也会出现问题
package main

/*#include<stdio.h>
  static const char* cs = "hellosss";
*/
import "C"

type CChar C.char

func (p *CChar)GoString() string {
	return C.GoString((*C.char)(p))
}
func PrintCString(cs *C.char) {
	C.puts(cs)
}
func main()  {
	PrintCString(C.cs)
}
error:undefined reference to `cs'

**Comment by chai2010** [comment]
static应该只是C代码所在的文件可见，其它的文件看不到

**Comment by whtiehack** [comment]
把static去掉就能找到。我只能这样理解， 虽然代码在一个文件里，但是编译时 c部分的代码还是单独的一个文件（也的确是单独的一个文件）。go部分代码编译出来的是另一个文件。

**Comment by felix0080** [comment]
上述从文中摘下来的 加了static，我现在去掉之后就可以了，看来staic只能在注释区C代码中应用

**Comment by felix0080** [comment]
谢谢指导，我懂了 @chai2010 @whtiehack
