### ISSUE TITLE
2.1.3 使用自己的C函数

### ISSUE THREAD

**Issue by memsethz** [chai2010/advanced-go-programming-book#421]
**2.1.3 使用自己的C函数** 将<SayHello函数放到当前目录下的一个C语言源文件中>这一小节中,  我跟着例子跑有问题. 
文中建立了一个 hello.c 文件放SayHello函数的实现, 但是在go源码中没有引入这个 .c 文件仅有一个声明, 编译会报错: /tmp/go-build/command-line-arguments/_obj/cgo-gcc-prolog:37：对‘SayHello’未定义的引用, 引入 .c 文件编译就没事了 ..
另外, 我想问下为啥在goland ide中运行这一节的程序, 只要涉及到C语言调用的输出, 就不会输出到goland的运行窗口, 在命令行下运行输出是没问题的

**Comment by chai2010** [comment]
Go代码需要声明C函数，看后面的代码：

```go
package main

//void SayHello(const char* s);
import "C"

func main() {
	C.SayHello(C.CString("Hello, World\n"))
}
```

**Comment by memsethz** [comment]
这是我在我本地机器运行的结果
![result](https://i.ibb.co/HhDNQdY/bug.png)

**Comment by memsethz** [comment]
需要我提供出go的配置路径之类的吗?

**Comment by chai2010** [comment]
go run .
或
go run main.go hello.c
试试

**Comment by memsethz** [comment]
> go run .

 这个命令会提示 go run: no go files listed

>  go run main.go hello.c

这个命令会提示未定义引用的同样错误信息
#command-line-arguments
/tmp/go-build712426445/command-line-arguments/_obj/main.cgo2.o：在函数‘_cgoa7fc76247_Cfunc_SayHello’中：
/tmp/go-build/command-line-arguments/_obj/cgo-gcc-prolog:37：对‘SayHello’未引用
collect2: error: ld returned 1 exit status

 go语言的版本为go1.9.2 linux/amd64

**Comment by chai2010** [comment]
```
$ go version
go version go1.12 darwin/amd64
$ go run .
Hello, World
```

没有问题，如果实在不行，可以尝试先`go build`再运行

**Comment by memsethz** [comment]
go build 能行
