### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by samuelyao314** [chai2010/advanced-go-programming-book#432]
提示：哪一章节的问题，建议如何修改
针对这本书的用户是, 在针对Go语言有一定经验想深入了解Go语言各种高级用法的开发人员。 我个人认为:   第一章部分实在有点多余.   倒是1.6 常用的并发模式,  可以是整理很多, 而且是难点.  例如哲学家问题等等.   个人觉的反射的实际使用, 也是高级的内容.   Go 圣经里语焉不详,

**Comment by cch123** [comment]
现在应该是基本定稿了。。要是开新坑的话可以考虑一下

**Comment by cch123** [comment]
顺便说一句，并发模式可以看看  concurrency in go 这本书，大部分都覆盖到了，中文资料大多也是对这本书内容的再加工
