### ISSUE TITLE
2.1.3中有一個示例不正確

### ISSUE THREAD

**Issue by kasim** [chai2010/advanced-go-programming-book#445]
在以下的部份，我用的go version 是 go version go1.12.2 linux/amd64

除了SayHello函数是我们自己实现的之外，其它的部分和前面的例子基本相似。

我们也可以将SayHello函数放到当前目录下的一个C语言源文件中（后缀名必须是.c）。因为是编写在独立的C文件中，为了允许外部引用，所以需要去掉函数的static修饰符。

// hello.c

#include <stdio.h>

void SayHello(const char* s) {
	puts(s);
}
然后在CGO部分先声明SayHello函数，其它部分不变：

// hello.go
package main

//void SayHello(const char* s);
import "C"

func main() {
	C.SayHello(C.CString("Hello, World\n"))
}

在和main 那個go file 相同目錄下創建了 hello.c 後，根據示例我的機器行不通。

要把go file 的內容改成

package main

// #include "hello.c"
import "C"

func main() {
	C.SayHello(C.CString("Hello, World\n"))
}

**Comment by chai2010** [comment]
SayHello的参数去掉const试试

**Comment by ShiinaOrez** [comment]
柴先生，2.1.3节的示例，建议注明运行方式来提醒读者：
运行命令为``go build -o main && ./main``而并非``go run ./main.go``（go源文件为main.go的情况）
@kasim 您的错误如上可以解决
附：go run 的错误报告

环境：Ubuntu 18.04 golang 1.10.1 linux/amd64
错误报告：

```terminal
# command-line-arguments
/tmp/go-build414046767/b001/_x002.o：在函数‘_cgo_ceddff67ea0a_Cfunc_SayHello’中：
/tmp/go-build/cgo-gcc-prolog:37：对‘SayHello’未定义的引用
collect2: error: ld returned 1 exit status
```
