### ISSUE TITLE
4.4.4发布和订阅模式

### ISSUE THREAD

**Issue by AaronLux** [chai2010/advanced-go-programming-book#470]
2009年7月第1版P229-P230中：
“其中Docker项目中提供了一个pubsub的极简实现，下面是基于……”
代码中最后 <- make(chan bool)  会造成死锁。

**Comment by chai2010** [comment]
`<-make(chan bool)`的作用是阻塞`main`函数提前退出。这个例子要展示的是在main退出之前收到订阅的消息。在真实的场景生产和消费会一直运行，因此这个地方本意是阻止main退出（如果需要退出程序需要在其它地方调用`os.Exit()`）。
