### ISSUE TITLE
5.3.3 更优雅的中间件写法 疑问

### ISSUE THREAD

**Issue by peachestao** [chai2010/advanced-go-programming-book#478]
您好，我是书的读者，

关于“5.3.3 更优雅的中间件写法“中的内容需要请教

r = NewRouter()
r.Use(logger)
r.Use(timeout)
r.Use(ratelimit)
r.Add("/", helloHandler)

后续该如何将r挂载到http服务上呢？

**Comment by cch123** [comment]
http.ListenAndServe(":3333", r)

**Comment by peachestao** [comment]
@cch123 http.ListenAndServe(":3333", r) 这样写需要r实现接口ServeHTTP(w http.ResponseWriter,r *http.Request)方法才行，我的意思是还有很多代码书中没有写出来，包活helloHandler该怎么写。能补全或者有参考的例子吗？

**Comment by cch123** [comment]
@peachestao ，具体的实现大多框架比较类似，可以看看这个：https://github.com/go-chi/chi

**Comment by peachestao** [comment]
@cch123 谢谢！
