### ISSUE TITLE
数组是值传递

### ISSUE THREAD

**Issue by shanghai-Jerry** [chai2010/advanced-go-programming-book#479]
在负载均衡中的洗牌算法中，违背了数组是值传递这一个大坑

` shuffle(slice []int)` 根本没有用到slice，就算用到里面修改数组也达不到实际的效果。

建议将数组作为全局变量（我猜作者本意也是如此，因为函数值根本没用到参数）

**Comment by cch123** [comment]
这里的示例代码写的确实有问题，不过在函数中修改 slice 是会影响原来的 slice 的，这个你可以简单做个实验

```
package main

import (
	"fmt"
	"math/rand"
)

// 重点在这个 shuffle
func shuffle(slice []int) {
	for i := 0; i < len(slice); i++ {
		a := rand.Intn(len(slice))
		b := rand.Intn(len(slice))
		slice[a], slice[b] = slice[b], slice[a]
	}
}

func main() {
	var endpoints = []int{
		1, 2, 3, 4, 5, 6,
	}
	shuffle(endpoints)
	fmt.Println(endpoints)
	shuffle(endpoints)
	fmt.Println(endpoints)
}
```

**Comment by shanghai-Jerry** [comment]
> 这里的示例代码写的确实有问题，不过在函数中修改 slice 是会影响原来的 slice 的，这个你可以简单做个实验
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 	"math/rand"
> )
> 
> func shuffle(slice []int) {
> 	for i := 0; i < len(slice); i++ {
> 		a := rand.Intn(len(slice))
> 		b := rand.Intn(len(slice))
> 		slice[a], slice[b] = slice[b], slice[a]
> 	}
> }
> 
> func main() {
> 	var endpoints = []int{
> 		1, 2, 3, 4, 5, 6,
> 	}
> 	shuffle(endpoints)
> 	fmt.Println(endpoints)
> 	shuffle(endpoints)
> 	fmt.Println(endpoints)
> }
> ```

是的
