### ISSUE TITLE
1.4.3 接口

### ISSUE THREAD

**Issue by anxinyf** [chai2010/advanced-go-programming-book#485]
1.4.3 最后一句话，”Go语言通过几种简单特性的组合，就轻易就实现了鸭子面向对象和虚拟继承等高级特性，真的是不可思议。“

”鸭子“在这里出现是什么意思？！要么删除这个词也是合理的。

**Comment by chai2010** [comment]
鸭子类型是一个技术术语，代表了和class不同的面向对象的设计哲学。
鸭子类型完整的说法是：走起来、叫起来都像鸭子，那么这个家伙就是鸭子。
特别的，在鸭子类型中，一个对象即可以是鸭子，又可以是地鼠或其它很多它可以魔法的对象；但是在class模式中一个对象就只能是一种class。

PS: 鸭子类型和画画思路很像，画的像鸭子就是鸭子。但是class思维的人会觉得画出来的鸭子不是真鸭子（因为不是从鸭蛋孵化来的）。
