### ISSUE TITLE
ch 1.1 在Go语言中，函数参数都是以复制的方式(不支持以引用的方式)传递

### ISSUE THREAD

**Issue by chenjinya** [chai2010/advanced-go-programming-book#486]
ch 1.1

最后一句
`在Go语言中，函数参数都是以复制的方式(不支持以引用的方式)传递（比较特殊的是，Go语言闭包函数对外部变量是以引用的方式使用）。`

```golang
func main() {
	var s string
	s = "456"
	haha(&s)
	fmt.Println(s)
}

func haha(c *string) {
	*c = "123"
}

```
输出 `123`

这样是以引用的方式传递吧？？？

还是我理解上有误会？

**Comment by chai2010** [comment]
调用`haha`的参数是`&s`，`&s`作为调用参数是无法在`haha`函数内部被修改的。或者说函数内部的对c本身的修改不会返回到调用者的`&s`.

**Comment by chenjinya** [comment]
理解。

**Comment by wpby** [comment]
> 调用`haha`的参数是`&s`，`&s`作为调用参数是无法在`haha`函数内部被修改的。或者说函数内部的对c本身的修改不会返回到调用者的`&s`.

无法在 haha 函数内部修改，那是在哪里修改的呢？
