### ISSUE TITLE
建议每一节都加上 上下文的链接

### ISSUE THREAD

**Issue by mulianju** [chai2010/advanced-go-programming-book#49]

**Comment by chai2010** [comment]
那需要再做一个目录，不然gitbook也会有这个链接。
建议你在gitbook那个页面浏览

**Comment by chai2010** [comment]
https://github.com/chai2010/advanced-go-programming-book/blob/master/SUMMARY.md
这里是目录

或者在gitbook看，可以翻页：
https://chai2010.gitbooks.io/advanced-go-programming-book/content/
