### ISSUE TITLE
2.7.3 C长期持有Go指针对象

### ISSUE THREAD

**Issue by wangjunqi001** [chai2010/advanced-go-programming-book#524]
提示：哪一章节的问题，建议如何修改
2.7.3 C长期持有Go指针对象

**Comment by wangjunqi001** [comment]
上文的声明参数使用的是C字符串
static void printString(const char* s) {
    char* gs = NewGoString(s);
    PrintGoString(gs);
    FreeGoString(gs);
}

//export NewGoString
func NewGoString(s *C.char) *C.char {
    gs := C.GoString(s)
    id := NewObjectId(gs)
    return (*C.char)(unsafe.Pointer(uintptr(id)))
}

而下文的调用是go字符串
func main() {
    C.printString("hello")
}

这会导致一个编译冲突
而将printString和NewGoString的参数改为_GoString_即可编译成功，也符合C长期持有Go对象这一话题

static void printStringV3(_GoString_ s) {
	char* id = NewGoString(s);
	PrintGoString(id);
	FreeGoString(id);
}

//export NewGoString
func NewGoString(s string) *C.char {
	id := NewObjectId(s)
	return (*C.char)(unsafe.Pointer(uintptr(id)))
}

不知道我的理解是否出现了偏差，求大神指正一二

**Comment by chai2010** [comment]
👍，代码写错了，`_GoString_`是比较合适的方式

**Comment by wangjunqi001** [comment]
好的，感谢大神回复~
