### ISSUE TITLE
顺序一致性内存模型

### ISSUE THREAD

**Issue by yue-qiu** [chai2010/advanced-go-programming-book#528]
你好，我刚开始接触到“顺序一致性内存模型”这个概念。我的理解是顺序一致性保证一个线程中所有操作必须按照代码编写的顺序来执行，但是文章提到在符合顺序一致性的单个线程里面也有可能发生指令重排的情况，这不就破环了顺序一致性了吗

**Comment by OkabeRintarou** [comment]
顺序一致性并不要求每个线程按照程序顺序来执行

**Comment by yue-qiu** [comment]
> 顺序一致性并不要求每个线程按照程序顺序来执行。
> 
> > The result of any execution is the same as if the operations of all the processors were executed in some sequential order, and the operations of each individual processor appear in this sequence in the order specified by its program.
> 
> 这里个人理解是，整个程序的执行存在一个全局的sequential order，对于某个线程来说，从这个全局order中挑选出该线程的执行order，只要该执行order的结果满足该线程的程序顺序执行结果，就满足顺序一致性。但该执行order可能并不一定严格等于程序序，可能发生了重排。

在保证顺序一致性的前提下对互不相关的指令进行重排

**Comment by cch123** [comment]
有逻辑依赖的会保证顺序，非逻辑依赖的可以并行执行(最后丢弃无效结果，比如 if  和 else 在 CPU 上可能并行执行)的，
因为现代 CPU 有多条指令流水线，比如之前 intel 的 spectre 和 meltdown 漏洞，理论上就是因为优化(乱序执行)导致的
