### ISSUE TITLE
因为要准备cgo报告, asm部分暂缓

### ISSUE THREAD

**Issue by chai2010** [chai2010/advanced-go-programming-book#53]
[GopherChina2018](http://gopherchina.org/) 要准备一个 《深入CGO编程》的报告，asm部分暂时没有精力准备。

cgo报告的内存比目前cgo的章节内容更加丰富，因此在报告初稿完成后会对cgo章节进行一次修订（但不是最终的修订），补充缺少的内容。

对cgo感兴趣的同学可以关注下，cgo中有许多烧脑的问题欢迎你来一起探讨。

报告最终也会放到网上。

**Comment by chai2010** [comment]
cgo报告初稿完成后，希望找人帮忙review下内容。
可以留言

**Comment by appleboy** [comment]
讚喔，非常期待。

**Comment by chai2010** [comment]
cgo 初稿已经完成，如果对 review 感兴趣的尽快留言（要有cgo使用经验，不然会看的很枯燥）。

一周内有效

**Comment by chai2010** [comment]
https://github.com/chai2010/gopherchina2018-cgo-talk
