### ISSUE TITLE
新版本的调度调整。这边可以说明一下？

### ISSUE THREAD

**Issue by xiaoliwang** [chai2010/advanced-go-programming-book#535]
https://github.com/chai2010/advanced-go-programming-book/blob/master/appendix/appendix-a-trap.md#L149

golang 1.14 版本引入基于系统信号的异步抢占调度。这边可以说明一下只有 1.14 之前的版本才会有饿死的问题？

**Comment by cch123** [comment]
可以的，欢迎提 PR 呀

**Comment by cch123** [comment]
Fixed by https://github.com/chai2010/advanced-go-programming-book/pull/537
