### ISSUE TITLE
1.3 节的 TrimSpace 函数会修改入参的切片

### ISSUE THREAD

**Issue by chenlujjj** [chai2010/advanced-go-programming-book#539]
1.3 节切片内存技巧里的函数：

`func TrimSpace(s []byte) []byte {
    b := s[:0]
    for _, x := range s {
        if x != ' ' {
            b = append(b, x)
        }
    }
    return b
}`
会改变传入的 s 切片，感觉不太妥当

**Comment by cch123** [comment]
cc @chai2010

**Comment by chai2010** [comment]
这个例子用slice的目的就是为了在原地修改，避免分配内存

**Comment by chenlujjj** [comment]
了解了，谢谢
