### ISSUE TITLE
方便在README.md里加个进度说明吗？

### ISSUE THREAD

**Issue by fzh890523** [chai2010/advanced-go-programming-book#54]
## Expected Behavior
如图，时不时更新一下。
谢谢。

**Comment by cch123** [comment]
关注更新的话可以直接 watch 这个项目~
我这边会尽快把 web 的部分更新完

**Comment by chai2010** [comment]
SUMMARY.md 可以看到大概进度。
至于进度计划，因为都是非全职写作，实在不好控制。

我今年的目标是 cgo 部分精校+汇编部分，其它内容就自由发展了。

**Comment by chai2010** [comment]
因为cgo和asm进展还比较顺利，因此小目标又稍微提高了一点。
大概的进度计划：6月完成asm章初版，9月完成rpc初版，争取年底收尾
