### ISSUE TITLE
请教个问题 关于字符串

### ISSUE THREAD

**Issue by givetimetolife** [chai2010/advanced-go-programming-book#549]
在1.3.2 字符串中，为什么说: 每个字符串的长度虽然也是固定的，但是字符串的长度并不是字符串类型的一部分。
但是Go语言字符串的底层结构包含一个len属性？
```
type StringHeader struct {
    Data uintptr
    Len  int
}
````

**Comment by chai2010** [comment]
"abc"和"a"是相同的类型，但是 `[3]rune{'a', 'b', 'c'}` 和 `[1]rune{'a'}` 则是不同的类型。
这是类型系统设计者的决策，和底层并无直接的关系

**Comment by givetimetolife** [comment]
我悟了! 感谢！
