### ISSUE TITLE
"完成"应该是"完整"

### ISSUE THREAD

**Issue by xiaosongfu** [chai2010/advanced-go-programming-book#55]
1.1. Go语言创世纪 中的倒数第二段中的"完成"应该是"完整"  

## Expected Behavior
" 最终这些package再有机地组成一个完整的Go语言程序 " 
## Actual Behavior
" 最终这些package再有机地组成一个完成的Go语言程序 " 

个人意见 ^_^

**Comment by chai2010** [comment]
https://github.com/chai2010/advanced-go-programming-book/commit/1c11ad083c52910d9b63d7c5528715bdcca090b8
