### ISSUE TITLE
关于 6.3 middleware 的一个问题

### ISSUE THREAD

**Issue by JokerBruceChan** [chai2010/advanced-go-programming-book#56]
## Expected Behavior

实际上只要你的 handler 函数签名是：

`func (ResponseWriter, *Request)`

那么这个 handler 就是一个 HandlerFunc 类型了，也就相当于实现了 http.Handler 这个接口，这要归功于 golang 的 duck typing 式的类型系统。

## Actual Behavior

如果我的 handler 函数签名是：

`func(ResponseWriter, *Request)`

并不能证明这个 handler 就是一个 HandlerFunc 类型，也并不是相当于实现了 http.Handler 这个接口。若想让自己的函数作为 http.Handler 接口类型使用，需要使用 http.HandlerFunc() 转换类型。

**Comment by cch123** [comment]
@JokerBruceChan ，这里确实写错了orz
马上修正

**Comment by cch123** [comment]
https://github.com/chai2010/advanced-go-programming-book/commit/805eae3f94b882ad1ed878a367c900c291bedd37

已修正，感谢反馈！
