### ISSUE TITLE
1.4开头对init函数中启动新goroutine的描述有错误

### ISSUE THREAD

**Issue by developerdong** [chai2010/advanced-go-programming-book#560]
> 要注意的是，在main.main函数执行之前所有代码都运行在同一个goroutine，也就是程序的主系统线程中。因此，如果某个init函数内部用go关键字启动了新的goroutine的话，新的goroutine只有在进入main.main函数之后才可能被执行到。

执行[这段代码](https://go.dev/play/p/Vxz0TkbjA4Y) 可以发现新的goroutine在init函数结束之前，也就是main函数开始之前就执行了，与文中所说不符。

**Comment by huanqingdong** [comment]
亲测, 不符
