### ISSUE TITLE
1.4.1 函数 闭包传值问题

### ISSUE THREAD

**Issue by huanqingdong** [chai2010/advanced-go-programming-book#570]
func main() {
	for i := 0; i < 3; i++ {
		i := i // 定义一个循环体内局部变量 i
		defer func(){ println(i) } ()
	}
}
这种修改方式输出的还是3个3, 没法解决闭包以引用方式访问i的问题

**Comment by cgyFight** [comment]
无论如何都不会输出3，最大也是2啊，你这是什么版本的go？
我的输出是2，1，0。感觉也能理解吧，for 中三次defer压栈，然后defer是在押入时传入的变量地址，中括号结束时，开始弹出，那么就是输出2，1，0.
如果defer之前没有使用i:=i，那传给defer的变量就是for中的i，这个i最后是啥就是啥了
