### ISSUE TITLE
转为 mdbook 格式，gitbook 可以退了

### ISSUE THREAD

**Issue by chai2010** [chai2010/advanced-go-programming-book#578]
欢迎大家提供帮助

**Comment by liuguangw** [comment]
gitbook生成pdf比较容易，而mdbook生成pdf就有点麻烦。我最近写了一个抓取在线文档制作pdf的工具：[pdf-builder](https://github.com/liuguangw/pdf-builder) ，我制作了一份pdf文档，效果还可以，pdf目录很完善，附上我制作的pdf：[advanced_go.pdf](https://github.com/chai2010/advanced-go-programming-book/files/9331221/advanced_go.pdf)。
![Snipaste_2022-08-13_18-18-56](https://user-images.githubusercontent.com/3318962/184479463-7bd7517d-410f-44d2-a3ba-4de7d850252c.png)

**Comment by wagaaa** [comment]
如果是出版物的话，可以考虑用LaTeX，虽然工作量会有点大😂
网络传播gitbook是流行一些

**Comment by chai2010** [comment]
@wagaaa 2019年本书就已经出版了，出版社只认word，我们也不会latex。

现在已经转到 mdbook，这个就关闭了，感谢关注
