### ISSUE TITLE
第 3 章 3.6.1 节 的 “图 3-13 函数调用参数布局” 有点小问题

### ISSUE THREAD

**Issue by hopehook** [chai2010/advanced-go-programming-book#583]
# Description of problem

问题点：
  - 第 3 章 汇编语言
    - 3.6.1 函数调用规范
      - 图 3-13 函数调用参数布局

# Expected result

“图 3-13 函数调用参数布局 ” 的最后一个位置，应当是  callee’s BP

```
callee's BP
(if framepointer_enabled)
```

# Actual result

目前描述的是 caller's BP

```
caller's BP
(if framepointer_enabled)
```

# Further information

因为是图片，我也没法提 PR，如果确实是个手误，麻烦 柴大 曹大 更正一下文字: `caller -> callee`。

![image](https://user-images.githubusercontent.com/7326168/180918724-13d9b7fd-0a40-49de-a977-e3c31063df50.png)

**Comment by chai2010** [comment]
图片是文本生成的，文件在image目录
