### ISSUE TITLE
ch1-04 上的一些疑问？

### ISSUE THREAD

**Issue by xiaoliwang** [chai2010/advanced-go-programming-book#65]
这一章提到第二个函数
> 内部虽然调用new函数创建了*int类型的指针对象，但是依然不知道它具体保存在哪里

```go
func f(x int) *int {
	return &x
}

func g() int {
    x := new(int)
    return *x
}
```

运行上面的代码，两者的地址都可以看到。请问*第二个函数不知道它具体保存在哪里*具体指的是什么意思？谢谢。

**Comment by xiaoliwang** [comment]
是不是指第一个函数变量本应该在**栈**上，但是从外部可以获取，所以可以推断是在**堆**上。
而后者是用 `new`，应该在 **堆**上。但是对于 `go` 来说，在**栈**或**堆**上都有可能

**Comment by chai2010** [comment]
是的，Go的语言规范是没有堆和栈堆概念的。

堆和栈只是某些实现强制引入堆概念（不要拿C语言规范作为Go的规范），
当然，Go的汇编也是有栈这些概念的，但是Go汇编并不是Go语言。

唯一的标准是Go语言规范，然后是满足规范的前提下包装程序正确运行。
二某些实现，你可以假设它总是性能最差的实现，只有正确就行。

new 和 `&T` 只是写法的区别，如何实现语言规范是没有规定的。
可以一样，也可能不一样。

**Comment by cch123** [comment]
前几天我也研究了一下这个问题。。

在不开优化直接 写new T 或者 &T{} 的情况下，用 go tool compile -S，看两者的汇编表现是不一样的，猜测后者被翻译成了两步操作，1 T{}, 2 &取地址，而 new 就是直接分配空间返回地址了

不过开了优化的话两者的汇编是完全一样的，具体在堆还是在栈上得看逃逸分析的结果
