### ISSUE TITLE
请教和建议

### ISSUE THREAD

**Issue by cloudzhou** [chai2010/advanced-go-programming-book#67]
1 Golang 的源代码已经支持 BOM 头的 utf8 文件

2 原文：错误编码不会向前扩散是UTF8编码的优秀特性之一
   疑点：这个看起来应该是 “向后” 扩散，不过这可能是我们对 “前”，“后” 理解的不同

3 原文：因为Go线程的启动是非阻塞的， main 线程显式休眠了1秒钟退出 导致程序结束，我们可以近似地认为程序总共执行了1秒多时间。现在假设 println 函数内部 实现休眠的时间大于 main 线程休眠的时间的话，就会导致矛盾：后台线程既然先于 main 线 程完成打印，那么执行时间肯定是小于 main 线程执行时间的。当然这是不可能的。
  疑点：这句话觉得比较拗口，读了几遍也不大理解

4 原文：对于带缓冲的Channel，对于Channel的第K个接收完成操作发生在第K+C个发送操作完成之 前，其中C是Channel的缓存大小。
  疑点：这句话容易让用户觉得，接收完成操作是在缓存满了之后开始。实际上，缓存的 Channel，不管 C 长度多少，只要有接收和发送，都是立即开始的。举个例子，一个 Channel 长度 100，send 和 receive 的 Goroutine 都在运行，那么可以说 send 1，然后 receive 1

**Comment by chai2010** [comment]
1. BOM的支持应该是有限的（具体是Go代码和普通文本），我没有详细跟进这个。如果有详细建议可以提交pr
2. 是的，我好像将前后弄反对，欢迎PR
3. 这个类似反证法，通过得出矛盾，证明sleep是不保险对（但是也不能得出绝对失败的结论）
4. chan有Len和Cap之分，是不是我们各自的理解有差异？

**Comment by chai2010** [comment]
第二点已经修复。
