### ISSUE TITLE
ch3 汇编语言 开工

### ISSUE THREAD

**Issue by chai2010** [chai2010/advanced-go-programming-book#70]
1. 目录调整(Done)
1. 第一节, 快速入门(Done)
1. 第二节, 计算机结构(Done)
1. 第三节, 常量和变量(Done)
1. 第四节, 函数(Done)
1. 第五节, 控制流(Done)
1. 第六节, 再论函数(Done)
1. ？

PS: 我也是汇编新手，如果大家发现错误，欢迎指出！非常感谢

**Comment by templexxx** [comment]
私以为要用到汇编主要是两个场景：

**Comment by chai2010** [comment]
@templexxx 目前定位是Go汇编语言本身。因为我字节对汇编也缺乏实战，对这个话题也无法提供参考。感觉你说对第一点很有意思，如果进展到相关内容再详细请教你。第二点可能会作为例子稍微提一下，重点还是BYTE实现对新指令对支持。第三点，当时你那个关于汇编优化对讲座，感觉对于普通读者太深了（我当前也没太听懂）

其实汇编对我也是现学现卖，在战争中学习战争。现慢慢充实内容，有了内容之后才好裁剪。

感谢你的建议

**Comment by chai2010** [comment]
ch3-02 暂时完结，后续再慢慢改

**Comment by chai2010** [comment]
ch3-03 done

**Comment by chai2010** [comment]
ch3-04 done

**Comment by chai2010** [comment]
ch3-05 done

**Comment by chai2010** [comment]
ch3-06 done

**Comment by chai2010** [comment]
为了继续赶后面的进度，先完结asm章。
asm还需要继续充电，以后还会再回来的
