### ISSUE TITLE
电子书的书名应该改下

### ISSUE THREAD

**Issue by wencan** [chai2010/advanced-go-programming-book#72]
当前名称为：“advanced-go-programming-book”
传送到kindle，也是这个名称

**Comment by chai2010** [comment]
没有明白，具体是希望怎么改呢？

**Comment by wencan** [comment]
书名，或者说标题，也该为：“Go语言高级编程”
但什么原因导致标题变成：“advanced-go-programming-book”??

**Comment by chai2010** [comment]
github的项目名称只能是英文字母和链接符等少数符号。
同时也是想避免在 url 中出现汉字。

将 url 或 github 项目 id 用作标题可能导致不太一样等内容。
我也不青春 github 是否可以在不改变 url 的 前提下设置标题。
