### ISSUE TITLE
附录中对“Goroutine饿死”相关知识的表述不准确

### ISSUE THREAD

**Issue by wencan** [chai2010/advanced-go-programming-book#73]
附录go坑章节中讲到：
“Goroutine是协作式调度, Goroutine本身不会主动放弃CPU”
这种表叙并不准确。网上很多类似的表述。

个人认为比较准确的表述：
“G-P-M模型的实现算是Go scheduler的一大进步，但Scheduler仍然有一个头疼的问题，那就是不支持抢占式调度，导致一旦某个G中出现死循环或永久循环的代码逻辑，那么G将永久占用分配给它的P和M，位于同一个P中的其他G将得不到调度，出现“饿死”的情况。更为严重的是，当只有一个P时(GOMAXPROCS=1)时，整个Go程序中的其他G都将“饿死”。于是Dmitry Vyukov又提出了《Go Preemptive Scheduler Design》并在Go 1.2中实现了“抢占式”调度。

这个抢占式调度的原理则是在每个函数或方法的入口，加上一段额外的代码，让runtime有机会检查是否需要执行抢占调度。这种解决方案只能说局部解决了“饿死”问题，对于没有函数调用，纯算法循环计算的G，scheduler依然无法抢占。”
源自：https://tonybai.com/2017/06/23/an-intro-about-goroutine-scheduler/

**Comment by wencan** [comment]
@cch123 
谢谢指出

“当前goroutine的“抢占式”调度依靠的是compiler在函数中自动插入的“cooperative preemption point”来实现的，但这种方式在使用过程中依然有各种各样的问题，比如：检查点的性能损耗、诡异的全面延迟问题以及调试上的困难。近期负责go runtime gc设计与实现的Austin Clements提出了一个proposal：non-cooperative goroutine preemption ，该proposal将去除cooperative preemption point，而改为利用构建和记录每条指令的stack和register map的方式实现goroutine的抢占， 该proposal预计将在go 1.12中实现。”
源自：https://tonybai.com/2018/04/06/the-problems-i-encountered-when-writing-go-code-issue-3rd/

**Comment by chai2010** [comment]
已经改为“协作式抢占调度”
