### ISSUE TITLE
附录中对"不同Goroutine之间不满足顺序一致性内存模型"的举例不恰当

### ISSUE THREAD

**Issue by 759803573** [chai2010/advanced-go-programming-book#77]
我自己理解的附录中的例子(见最下方) 发生的问题是在它之上描述的`独占CPU导致其它Goroutine饿死`的问题

当在for 循环中加入`runtime.Gosched()`来使程序正常结束

觉得例子不是很恰当

```go
var msg string
var done bool = false

func main() {
    runtime.GOMAXPROCS(1)

    go func() {
        msg = "hello, world"
        done = true
    }()

    for {
        if done {
            println(msg)
            break
        }
    }
}
```

**Comment by cch123** [comment]
@759803573 ，加 gosched 也是有成本的，这里就是给个例子~

这个问题实际上在社区也讨论的蛮久的了，给你几个参考链接：

出问题时的定位：
http://xargin.com/how-to-locate-for-block-in-golang/

1.9 之前的讨论：
https://github.com/golang/go/issues/10958

1.12 的新的解决方案：
https://github.com/golang/go/issues/24543

**Comment by chai2010** [comment]
这是从官网摘的例子：https://golang.org/ref/mem#tmp_10

这个问题比较难以重现。我也无法清楚描述这个问题。

建议先看看官网的例子
